version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - recruitment-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - recruitment-network

networks:
  recruitment-network:
    driver: bridge

volumes:
  mongodb_data:
